### ISSUE TITLE
VSCode stopped working after upgrade from 1.78.2 to 1.79

### ISSUE THREAD

**Issue by waynebloss** [ArturoDent/command-alias#6]
Type: <b>Bug</b>

Hello - I'm not sure what the issue is but VSCode helped me narrow it down to this extension. The bug caused no extensions to be recognized (in settings.json for instance) - the extensions were still listed but almost all context menu items were disabled for them and the listings were all greyed out... The symptom that alerted me to the problem initially was that I could not open the Release Notes or Welcome page immediately after I upgraded visual-studio-code-bin (1.78.2-1 -> 1.79.0-1) on Manjaro (Arch) Linux.

Extension version: 0.6.0
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:28:44.251Z)
OS version: Linux x64 5.15.114-2-MANJARO

<details>
<summary>Here's what I found in the log:</summary>

```log
2023-06-08 19:08:58.989 [error] Cannot read properties of undefined (reading '_lower'): TypeError: Cannot read properties of undefined (reading '_lower')
    at C.toKey (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:656:8213)
    at S.get (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:656:8608)
    at e.ExtensionRunningLocationTracker.l (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:11783)
    at e.ExtensionRunningLocationTracker.initializeRunningLocation (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:12441)
    at e.NativeExtensionService.ib (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:19698)
    at e.NativeExtensionService.hb (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:19280)
2023-06-08 19:08:59.098 [error] Cannot read properties of undefined (reading '_lower'): TypeError: Cannot read properties of undefined (reading '_lower')
    at C.toKey (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:656:8213)
    at S.get (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:656:8608)
    at e.ExtensionRunningLocationTracker.l (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:11783)
    at e.ExtensionRunningLocationTracker.computeRunningLocation (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:11331)
    at Object.getInitData (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:15857)
    at async e.NativeLocalProcessExtensionHost.J (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1635:8698)
```
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|31.26GB (28.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by ArturoDent** [comment]
Thanks for the report.  How did VSCode help you to figure out this extension was an issue?  There isn't anything in the log related to the extension.

I had issues with the v1.79 update too and have `Command Alias` installed as well.  But eventually the problem went away with some restarts, etc. (I am not sure how it got fixed) but I never uninstalled any extensions and the Extension Bisect was unhelpful.

**Comment by waynebloss** [comment]
I used the Extension Bisect. After it disabled this extension and restarted, everything was working again.

**Comment by ArturoDent** [comment]
From Claude Code:

> Every time VS Code starts (or the extension host restarts, e.g. on "Reload Window"), it scans the extensions directory and does this entirely in memory, inside the Extension Host process (a separate Node.js process, but still just RAM):
> 
> 1. Reads your `package.json` off disk with plain file I/O — the real, unmodified file.  
> 2. `JSON.parses` it.  
> 3. Builds an internal bookkeeping object (IExtensionDescription) by taking that parsed content and adding the extra computed fields (identifier, isBuiltin, extensionLocation, etc.) as properties on top.  
> 4. Hands that combined object to your code via `vscode.extensions.getExtension(id).packageJSON`.  
> 
> None of that touches the file on disk. VS Code recomputes this fresh, in RAM, every single session, and it never calls anything like `fs.writeFileSync` back into your extension's install directory to persist it. (VS Code does persist its own bookkeeping somewhere — extension state, `extensions.json` listings, etc. — but that lives in VS Code's own user-data directory, completely separate from your extension's source tree. It was never going to end up in your package.json on its own.)
> 
> Your extension's code is the only thing that ever wrote it to disk
> The old `loadCommands()` code took that in-memory enriched object — which your extension obtained legitimately via the documented `vscode.extensions.getExtension()` API — and then did something VS Code never does and never expects: called `fs.writeFileSync()` to dump that object back over the actual `package.json` file in the extension's own install directory.

....

> That's exactly why the fix works: once the write path stops reading from that enriched in-memory object and instead re-reads the raw file from disk before mutating just `contributes.commands`, there's no longer any code, anywhere in this extension, that ever moves those injected fields from RAM back onto disk.

------------

So apparently this issue: [[Extraneous data written to package.json while debugging an extension that writes to package.json](https://github.com/microsoft/vscode/issues/161286#top)](https://github.com/microsoft/vscode/issues/161286):

> It is recommended to read the package.json from the extension location to get the original contents.

:+1: The best is to read the file from disk, parse it, modify the JSON and then write it back to disk. As you have discovered, the packageJSON exposed via the API contains these additional properties. We exposed them by accident since the first time we supported extensions and now it is not safe to remove them, as some existing extensions might have taken a dependency on these properties being there.

--------------

I am using this code now:

```js
exports.getPackageJSON = async function () {

  const extensionPath = extensions.getExtension('ArturoDent.find-and-transform').extensionPath;
  
  const packageJSONUri = Uri.file(path.join(extensionPath, 'package.json'));
  const packageContents = (await workspace.fs.readFile(packageJSONUri)).toString();
  const packageJSON = JSON.parse(packageContents);

  return packageJSON;
}
```
---------------------------------------  

So I have incorporated that change into this extension to hopefully fix this issue.  Use v0.7.0 of this extension.
